### ISSUE TITLE
why execute this function twice? and also how is the plot viewed?

### ISSUE THREAD

**Issue by trevorspreadbury** [uchicago-dsi/climate-cabinet-campaign-finance-tracker#86]
```
    #TODO: why execute this function twice? and also how is the plot viewed?
```

https://github.com/dsi-clinic/2024-winter-climate-cabinet-campaign-finance-tracker/blob/6289156899c02b94711ae953786dde51884520cf/src/utils/network.py#L301

**Comment by bhavyapan** [comment]
There is no need for twice execution - it seems like an error. I am addressing this. Further, to view graphs, the pipeline function must be called. Then, there are two options for displaying graphs, enlisted below. It is important to note that these are interactive visualizations created using `Plotly` and are dynamic in nature, rather than simple plots:
- [So far, I have only tried this locally] In the VS Code environment, right click on an empty line in the open `network.py` file > Run in Interactive Window > Run Current File in Interactive Window. This opens up a temporary interactive view and allows one to view and interact with the interactive visualization created.
- I am changing the `plot_network_graph` function to save `.html` files with interactive visualizations in a directory called `graphs`. These files can be opened up using any browser and viewed.

**Comment by trevorspreadbury** [comment]
Sounds good!
